server.port=8081

spring.datasource.url=jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never

jwt.secret=ACPSRI/H9XbmJIPohg6F9Tjmx68TUDoG29zYsRE0m18=
jwt.expiration-ms=3600000

# URLs dos outros serviços (monolito)
monolith.project.service.url=http://localhost:8080/api/projects
monolith.user.service.url=http://localhost:8080/api/users

